---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        argument:
          - -c
          - echo "Deploy on ${ENV_NAME} environment"

pipelines:
  java_microservice:
    group: microservices
    lock_behavior: unlockWhenFinished
    label_template: "${git_java_microservice}"
    materials:
      git_java_microservice:
        git: "https://github.com/NilsBerz/api_tests_ci.git"
        branch: main
        shallow_clone: true
        auto_update: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building java app"
      - deploy-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-dev:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Running tests on DEV"
      - deploy-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-int:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Running tests on INT"
      - deploy-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-prd:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Running tests on PRD"